# async_map with limit, error

    Code
      synchronise(async_map(list, fun, .limit = l))
    Condition
      Error in `fun()`:
      ! oops

---

    Code
      synchronise(async_map(list, fun, .limit = l))
    Condition
      Error in `fun()`:
      ! oops

---

    Code
      synchronise(async_map(list, fun, .limit = l))
    Condition
      Error in `fun()`:
      ! oops

---

    Code
      synchronise(async_map(list, fun, .limit = l))
    Condition
      Error in `fun()`:
      ! oops

---

    Code
      synchronise(async_map(list, fun, .limit = l))
    Condition
      Error in `fun()`:
      ! oops

---

    Code
      synchronise(async_map(list, fun, .limit = l))
    Condition
      Error in `fun()`:
      ! oops

---

    Code
      synchronise(async_map(list, fun, .limit = l))
    Condition
      Error in `fun()`:
      ! oops

---

    Code
      synchronise(async_map(list, fun, .limit = l))
    Condition
      Error in `fun()`:
      ! oops

---

    Code
      synchronise(async_map(list, fun, .limit = l))
    Condition
      Error in `fun()`:
      ! oops

---

    Code
      synchronise(async_map(list, fun, .limit = l))
    Condition
      Error in `fun()`:
      ! oops

---

    Code
      synchronise(async_map(list, fun, .limit = l))
    Condition
      Error in `fun()`:
      ! oops

